### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by dnousome**
Freec script requires GenomicRanges R package to run

### CODE REVIEW

**Comment by skchronicles** [comment]
Hey @dnousome,

I think `rtracklayer` installs `GenomicRanges` as a dependency. I would need to double check this tomorrow, but are you getting an error about the package being missing?

**Comment by skchronicles** [comment]
Hey @dnousome,

I just had some time to check if `GenomicRanges` is installed in the image. 

It is already installed:
```
$ docker run -ti nciccbr/ccbr_wes_base:v0.1.0 /bin/bash
root@35c7ab1b88ce:/data2# R

R version 4.1.2 (2021-11-01) -- "Bird Hippie"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(GenomicRanges)
Loading required package: stats4
Loading required package: BiocGenerics

Attaching package: 'BiocGenerics'

The following objects are masked from 'package:stats':

    IQR, mad, sd, var, xtabs

The following objects are masked from 'package:base':

    Filter, Find, Map, Position, Reduce, anyDuplicated, append,
    as.data.frame, basename, cbind, colnames, dirname, do.call,
    duplicated, eval, evalq, get, grep, grepl, intersect, is.unsorted,
    lapply, mapply, match, mget, order, paste, pmax, pmax.int, pmin,
    pmin.int, rank, rbind, rownames, sapply, setdiff, sort, table,
    tapply, union, unique, unsplit, which.max, which.min

Loading required package: S4Vectors

Attaching package: 'S4Vectors'

The following objects are masked from 'package:base':

    I, expand.grid, unname

Loading required package: IRanges
Loading required package: GenomeInfoDb
```

**Comment by dnousome** [comment]
I was having issues with freec loading the package during the
assess_significance.R script which didn't run because of the dependency.
May be due to the envmodule part instead of the docker. Will take a look
again.

**Comment by skchronicles** [comment]
Okay, sounds good @dnousome. 

Yeah, right now the entire pipeline is using docker images for every step. If you want, I can take a look at what you are doing. I just checked and it also looks like the `rtracklayer` is loading `GenomicRanges` correctly under the hood:
```
$  docker run -ti nciccbr/ccbr_wes_base:v0.1.0 /bin/bash
root@ba3b3e90ac70:/data2# R

R version 4.1.2 (2021-11-01) -- "Bird Hippie"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(rtracklayer)
Loading required package: GenomicRanges
Loading required package: stats4
Loading required package: BiocGenerics

Attaching package: 'BiocGenerics'

The following objects are masked from 'package:stats':

    IQR, mad, sd, var, xtabs

The following objects are masked from 'package:base':

    Filter, Find, Map, Position, Reduce, anyDuplicated, append,
    as.data.frame, basename, cbind, colnames, dirname, do.call,
    duplicated, eval, evalq, get, grep, grepl, intersect, is.unsorted,
    lapply, mapply, match, mget, order, paste, pmax, pmax.int, pmin,
    pmin.int, rank, rbind, rownames, sapply, setdiff, sort, table,
    tapply, union, unique, unsplit, which.max, which.min

Loading required package: S4Vectors

Attaching package: 'S4Vectors'

The following objects are masked from 'package:base':

    I, expand.grid, unname

Loading required package: IRanges
Loading required package: GenomeInfoDb
> help(GRanges)
> GRanges 
function (seqnames = NULL, ranges = NULL, strand = NULL, ..., 
    seqinfo = NULL, seqlengths = NULL) 
{
    mcols <- DataFrame(..., check.names = FALSE)
    if (!is.null(ranges)) {
        ranges <- as(ranges, "IRanges")
    }
    else if (is.null(seqnames)) {
        ranges <- IRanges()
    }
    else {
        x <- as(seqnames, "GRanges")
        seqnames <- x@seqnames
        ranges <- x@ranges
        if (is.null(strand)) 
            strand <- x@strand
        if (length(mcols) == 0L) 
            mcols <- mcols(x, use.names = FALSE)
        if (is.null(seqinfo)) 
            seqinfo <- seqinfo(x)
    }
    seqinfo <- normarg_seqinfo2(seqinfo, seqlengths)
    ans <- new_GRanges("GRanges", seqnames = seqnames, ranges = ranges, 
        strand = strand, mcols = mcols, seqinfo = seqinfo)
    validObject(ans)
    ans
}
<bytecode: 0x5558dca86b68>
<environment: namespace:GenomicRanges>
> 
```

**Comment by dnousome** [comment]
@skchronicles, sorry for the delay. Looks like everything is installed correctly when the docker image is pulled.

I think there must have been an R module still running which messed with the .libPaths() where all the packages were installed.

Thanks for taking a look! I'll close the issue now

**Pull request closed without merging**
